### PR TITLE
example added for sorting

### PR DESCRIPTION
**Pull request by vanAmsterdam**
Using a trivial sort function, the plot can be sorted in order of
occurrence. This allows users to order their data in R without having
to know JavaScript.

### CODE REVIEW

**Comment by timelyportfolio** [comment]
Thanks so much for this.  Sorry I somehow missed it.  I will get this merged over the next couple of days.

**Comment by timelyportfolio** [comment]
@vanAmsterdam, will add into the grand `d3v4` refactor #36

**Comment by timelyportfolio** [comment]
Now merged.  I apologize again for taking so long on this.  Thanks so much for your contribution!

**Comment by vanAmsterdam** [comment]
no problem

**Pull request merged**
